-- NE PAS APPLIQUER.
--
-- Cette migration locale a ete neutralisee le 2026-05-02.
-- Raison: la base Supabase V1 reelle utilise le schema dossiers/lignes_facturables
-- et ne contient pas les anciennes tables referencees par la version precedente
-- de ce fichier, notamment public.depannages.
--
-- Aucune instruction SQL executable ne doit etre ajoutee ici sans confirmation
-- complete des colonnes reelles de production.
